<!--
a = 2;if(a==0){a=1}
var slump = Math.random();
var talet = Math.round(slump * (a-1))+1;
function create() { 
this.under = '' 
}
b = new Array() 
for(var i=1; i<=a; i++) { b[i] = new create() } 
b[1].under ='<font color="red">[广告] </font><a target="_blank" href="Http://Www.cnhww.Com"><font color="blue">网趣网上购物系统，是国内功能最强大的网上购物系统.....</font></a>'
b[2].under ='<font color="red">[广告] </font><a target="_blank" href="http://www.cnhww.com/fshop/trends.asp?id=75"><font color="blue">网趣网上购物系统的几十大功能特点强先看.....</font></a>'
var visa = "";
document.write(b[talet].under); 
//-->